<a href="https://colab.research.google.com/github/adllzmly-sketch/pm-turi2-preprocessing-AdelZamalya/blob/main/PM_P4_AdelZamalya_2488010059.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset

In [32]:
import pandas as pd

data = {
    'usia': [23, 25, None, 30, 28, 35, None, 27, 32, 24],
    'pendapatan': [3000000, 4000000, 3500000, None, 5000000, 6000000, 4500000, None, 7000000, 3200000],
    'pendidikan': ['SMA', 'S1', 'S1', 'S2', 'S1', 'S2', 'SMA', 'S1', 'S2', 'SMA'],
    'kota': ['Cirebon', 'Kuningan', 'Majalengka', 'Cirebon', 'Kuningan',
             'Majalengka', 'Cirebon', 'Kuningan', 'Majalengka', 'Cirebon'],
    'membeli': ['Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak']
}

df = pd.DataFrame(data)

df

   usia  pendapatan pendidikan        kota membeli
0  23.0   3000000.0        SMA     Cirebon   Tidak
1  25.0   4000000.0         S1    Kuningan      Ya
2   NaN   3500000.0         S1  Majalengka      Ya
3  30.0         NaN         S2     Cirebon      Ya
4  28.0   5000000.0         S1    Kuningan   Tidak
5  35.0   6000000.0         S2  Majalengka      Ya
6   NaN   4500000.0        SMA     Cirebon   Tidak
7  27.0         NaN         S1    Kuningan      Ya
8  32.0   7000000.0         S2  Majalengka      Ya
9  24.0   3200000.0        SMA     Cirebon   Tidak

# Langkah 1

In [41]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

display(df)

   usia  pendapatan pendidikan        kota membeli
0  23.0   3000000.0        SMA     Cirebon   Tidak
1  25.0   4000000.0         S1    Kuningan      Ya
2  27.5   3500000.0         S1  Majalengka      Ya
3  30.0   4250000.0         S2     Cirebon      Ya
4  28.0   5000000.0         S1    Kuningan   Tidak
5  35.0   6000000.0         S2  Majalengka      Ya
6  27.5   4500000.0        SMA     Cirebon   Tidak
7  27.0   4250000.0         S1    Kuningan      Ya
8  32.0   7000000.0         S2  Majalengka      Ya
9  24.0   3200000.0        SMA     Cirebon   Tidak

# Langkah 2

In [43]:
x = df.drop(columns=['membeli'])
y = df['membeli']

print("Fitur (X):")
display(x)

print("Label (y):")
display(y)

Fitur (X):

   usia  pendapatan pendidikan        kota
0  23.0   3000000.0        SMA     Cirebon
1  25.0   4000000.0         S1    Kuningan
2  27.5   3500000.0         S1  Majalengka
3  30.0   4250000.0         S2     Cirebon
4  28.0   5000000.0         S1    Kuningan
5  35.0   6000000.0         S2  Majalengka
6  27.5   4500000.0        SMA     Cirebon
7  27.0   4250000.0         S1    Kuningan
8  32.0   7000000.0         S2  Majalengka
9  24.0   3200000.0        SMA     Cirebon

Label (y):

0    Tidak
1       Ya
2       Ya
3       Ya
4    Tidak
5       Ya
6    Tidak
7       Ya
8       Ya
9    Tidak
Name: membeli, dtype: object

# Langkah 3

In [44]:
x['pendidikan'] = x['pendidikan'].map({'SMA':0, 'S1' :1, 'S2':2})
x = pd.get_dummies(x, columns=['kota'], dtype=int)
y = y.map({'Tidak':0, 'Ya':1})

print("X setelah encoding:")
display(x)

print("y setelah encoding:")
display(y)

X setelah encoding:

   usia  pendapatan  pendidikan  kota_Cirebon  kota_Kuningan  kota_Majalengka
0  23.0   3000000.0           0             1              0                0
1  25.0   4000000.0           1             0              1                0
2  27.5   3500000.0           1             0              0                1
3  30.0   4250000.0           2             1              0                0
4  28.0   5000000.0           1             0              1                0
5  35.0   6000000.0           2             0              0                1
6  27.5   4500000.0           0             1              0                0
7  27.0   4250000.0           1             0              1                0
8  32.0   7000000.0           2             0              0                1
9  24.0   3200000.0           0             1              0                0

y setelah encoding:

0    0
1    1
2    1
3    1
4    0
5    1
6    0
7    1
8    1
9    0
Name: membeli, dtype: int64

# Langkah 4

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

print("Pembagian Data:")
print("Jumlah data X_train:", len(x_train))
print("Jumlah data X_test:", len(x_test))
print("Jumlah data y_train:", len(y_train))
print("Jumlah data y_test:", len(y_test))

Pembagian Data:
Jumlah data X_train: 7
Jumlah data X_test: 3
Jumlah data y_train: 7
Jumlah data y_test: 3

# Langkah 5

In [46]:
from sklearn.preprocessing import StandardScaler
num = ['usia', 'pendapatan', 'pendidikan']
sc = StandardScaler()
x_train[num] = sc.fit_transform(x_train[num])
x_test[num] = sc.transform(x_test[num])

print("Data setelah scaling:")
display(x_train)
display(x_test)

Data setelah scaling:

,usia,pendapatan,pendidikan,kota_Cirebon,kota_Kuningan,kota_Majalengka
0,-1.662777,-1.404239,-1.020621,1,0,0
7,0.127906,0.429655,0.408248,0,1,0
2,0.351741,-0.670681,0.408248,0,0,1
9,-1.215106,-1.110816,-1.020621,1,0,0
4,0.575577,1.529992,0.408248,0,1,0
3,1.470918,0.429655,1.837117,1,0,0
6,0.351741,0.796434,-1.020621,1,0,0

,usia,pendapatan,pendidikan,kota_Cirebon,kota_Kuningan,kota_Majalengka
8,2.366259,4.464222,1.837117,0,0,1
1,-0.767435,0.062876,0.408248,0,1,0
5,3.709271,2.997107,1.837117,0,0,1

# Langkah 6

In [48]:
print("Jumlah nilai hilang:")
print(x_train.isnull().sum())

print("\nTipe data:")
print(x_train.dtypes)

print("\nStatistik data setelah scaling:")
display(x_train.describe())

Jumlah nilai hilang:
usia               0
pendapatan         0
pendidikan         0
kota_Cirebon       0
kota_Kuningan      0
kota_Majalengka    0
dtype: int64

Tipe data:
usia               float64
pendapatan         float64
pendidikan         float64
kota_Cirebon         int64
kota_Kuningan        int64
kota_Majalengka      int64
dtype: object

Statistik data setelah scaling:

,usia,pendapatan,pendidikan,kota_Cirebon,kota_Kuningan,kota_Majalengka
count,7.000000e+00,7.000000e+00,7.000000e+00,7.000000,7.000000,7.000000
mean,-4.202987e-16,-2.061843e-16,-9.516197e-17,0.571429,0.285714,0.142857
std,1.080123e+00,1.080123e+00,1.080123e+00,0.534522,0.487950,0.377964
min,-1.662777e+00,-1.404239e+00,-1.020621e+00,0.000000,0.000000,0.000000
25%,-5.436001e-01,-8.907485e-01,-1.020621e+00,0.000000,0.000000,0.000000
50%,3.517412e-01,4.296552e-01,4.082483e-01,1.000000,0.000000,0.000000
75%,4.636589e-01,6.130446e-01,4.082483e-01,1.000000,0.500000,0.000000
max,1.470918e+00,1.529992e+00,1.837117e+00,1.000000,1.000000,1.000000

# Latihan Mandiri

1

In [49]:
df_mean = pd.DataFrame(data)

df_mean['usia'] = df_mean['usia'].fillna(df_mean['usia'].mean())

print("Hasil imputasi menggunakan Mean:")
display(df_mean)

print("Nilai Mean usia:", df_mean['usia'].mean())

Hasil imputasi menggunakan Mean:

   usia  pendapatan pendidikan        kota membeli
0  23.0   3000000.0        SMA     Cirebon   Tidak
1  25.0   4000000.0         S1    Kuningan      Ya
2  28.0   3500000.0         S1  Majalengka      Ya
3  30.0         NaN         S2     Cirebon      Ya
4  28.0   5000000.0         S1    Kuningan   Tidak
5  35.0   6000000.0         S2  Majalengka      Ya
6  28.0   4500000.0        SMA     Cirebon   Tidak
7  27.0         NaN         S1    Kuningan      Ya
8  32.0   7000000.0         S2  Majalengka      Ya
9  24.0   3200000.0        SMA     Cirebon   Tidak

Nilai Mean usia: 28.0

2.

In [50]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

x_train_minmax = x_train.copy()
x_test_minmax = x_test.copy()

x_train_minmax[num] = scaler.fit_transform(x_train_minmax[num])
x_test_minmax[num] = scaler.transform(x_test_minmax[num])

print("Hasil MinMaxScaler:")
display(x_train_minmax.describe())

Hasil MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Cirebon,kota_Kuningan,kota_Majalengka
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,0.530612,0.478571,0.357143,0.571429,0.285714,0.142857
std,0.344681,0.368111,0.377964,0.534522,0.487950,0.377964
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.357143,0.175000,0.000000,0.000000,0.000000,0.000000
50%,0.642857,0.625000,0.500000,1.000000,0.000000,0.000000
75%,0.678571,0.687500,0.500000,1.000000,0.500000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

3.

In [51]:
df_kategori = pd.DataFrame(data)

df_kategori['status'] = [
    'Tetap',
    'Kontrak',
    'Tetap',
    'Tetap',
    'Kontrak',
    'Tetap',
    'Kontrak',
    'Tetap',
    'Tetap',
    'Kontrak'
]

print("Data sebelum one-hot encoding:")
display(df_kategori)

df_kategori = pd.get_dummies(
    df_kategori,
    columns=['status'],
    dtype=int
)

print("Data setelah one-hot encoding:")
display(df_kategori)

Data sebelum one-hot encoding:

   usia  pendapatan pendidikan        kota membeli   status
0  23.0   3000000.0        SMA     Cirebon   Tidak    Tetap
1  25.0   4000000.0         S1    Kuningan      Ya  Kontrak
2   NaN   3500000.0         S1  Majalengka      Ya    Tetap
3  30.0         NaN         S2     Cirebon      Ya    Tetap
4  28.0   5000000.0         S1    Kuningan   Tidak  Kontrak
5  35.0   6000000.0         S2  Majalengka      Ya    Tetap
6   NaN   4500000.0        SMA     Cirebon   Tidak  Kontrak
7  27.0         NaN         S1    Kuningan      Ya    Tetap
8  32.0   7000000.0         S2  Majalengka      Ya    Tetap
9  24.0   3200000.0        SMA     Cirebon   Tidak  Kontrak

Data setelah one-hot encoding:

,usia,pendapatan,pendidikan,kota,membeli,status_Kontrak,status_Tetap
0,23.0,3000000.0,SMA,Cirebon,Tidak,0,1
1,25.0,4000000.0,S1,Kuningan,Ya,1,0
2,NaN,3500000.0,S1,Majalengka,Ya,0,1
3,30.0,NaN,S2,Cirebon,Ya,0,1
4,28.0,5000000.0,S1,Kuningan,Tidak,1,0
5,35.0,6000000.0,S2,Majalengka,Ya,0,1
6,NaN,4500000.0,SMA,Cirebon,Tidak,1,0
7,27.0,NaN,S1,Kuningan,Ya,0,1
8,32.0,7000000.0,S2,Majalengka,Ya,0,1
9,24.0,3200000.0,SMA,Cirebon,Tidak,1,0

4.

fit_transform() digunakan pada data latih karena scaler perlu mempelajari karakteristik data latih terlebih dahulu, kemudian melakukan transformasi. Sedangkan pada data uji hanya menggunakan transform()

# Refleksi

1. agar informasi dari data uji tidak bocor ke pelatihan.

2. Label encoding digunakan untuk data ordinal yang membutuhkan urutan. One-hot encoding digunakan untuk data yang tidak membutuhkan urutan.

3. Normalisai  (min-max): Melakukan pensekalaaan berdasarkan nilai minimum dan maksimum. Standarisasi ( Z-Score) : mengubah ke nilai rata rata.